#!/usr/bin/env python3
"""
linkify-paths.py — turn existing file/directory paths in Markdown into links.

Recursively scans every ``*.md`` / ``*.markdown`` file under a root directory and
converts any token that points at a real file/directory (resolved relative to the
.md file that contains it) into a Markdown link ``[path](path)``.

Examples
--------
    `../tool-index.md`          ->  [../tool-index.md](../tool-index.md)
    Read ../tool-index.md       ->  Read [../tool-index.md](../tool-index.md)
    `scripts/decode.ps1`        ->  [scripts/decode.ps1](scripts/decode.ps1)
    `skills/apk-reverse/`       ->  [skills/apk-reverse/](skills/apk-reverse/)

What is left untouched
----------------------
    * fenced code blocks (``` ... ``` and ~~~ ... ~~~)
    * existing ``[text](url)`` links and ``![alt](img)`` images
    * autolinks (``<...>``) and ``http(s)://`` URLs
    * inline code whose whole content is NOT a single path (e.g. a full command)
    * tokens that do not resolve to an existing file/directory

Usage
-----
    # preview changes (does not write anything)
    python3 scripts/linkify-paths.py

    # actually rewrite the files
    python3 scripts/linkify-paths.py --apply

    # rewrite, keeping a .bak copy of every changed file
    python3 scripts/linkify-paths.py --apply --backup

    # only look at one subtree
    python3 scripts/linkify-paths.py skills/apk-reverse --apply

    # also link known-but-not-yet-generated filenames (see --known-missing)
    python3 scripts/linkify-paths.py --apply --known-missing tool-index.md,INDEX.md
"""

import argparse
import os
import re

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# File extensions that make a bare token "look like a path" even without a '/'.
KNOWN_EXTS = (
    r"md|markdown|ps1|sh|bash|py|json|ya?ml|toml|ini|conf|txt|rst|csv|tsv|log|"
    r"html?|xml|svg|png|jpe?g|gif|pdf|zip|g?z|xz|tar|bat|cmd|exe|dll|so|elf|"
    r"jar|apk|sql|db|pem|crt|key|p12|properties|gradle|lock|ts|js|css|c|cpp|h|"
    r"hpp|java|kt|go|rs|php|rb|lua|pl"
)

# Filenames treated as "exists" even when absent from disk.  ``tool-index.md``
# is gitignored in this repo and generated by the first-run bootstrap, so it is
# normally missing from a fresh clone — but it is still a real, intended path.
KNOWN_MISSING = {"tool-index.md"}

# Characters allowed inside a path token (note the backslash for Windows paths).
PATH_CHAR = r"[A-Za-z0-9_.@+~/\\-]"

# A path token must end in something other than '.' so that a trailing sentence
# period ("see README_AI.md.") is not swallowed into the token.
PATH_FINAL = r"[A-Za-z0-9_/@+~\\-]"

# ---------------------------------------------------------------------------
# Regexes
# ---------------------------------------------------------------------------

# Maximal run of path-like characters, ending in a non-dot char.  Each match is
# post-checked below; this deliberately over-matches so we can filter in
# `looks_like_path` / `target_exists`.
TOKEN_RE = re.compile(PATH_CHAR + r"*" + PATH_FINAL)

# Inline code spans.  Handled separately so we can drop the backticks when the
# whole span is a single path, and leave full commands alone.
INLINE_CODE_RE = re.compile(r"(`[^`]*`)")

# A line that opens/closes a fenced code block.
FENCE_LINE_RE = re.compile(r"^\s{0,3}(`{3,}|~{3,})")

# Things we protect verbatim (never touch) before processing, then restore.
MD_LINK_RE = re.compile(r"!?\[[^\]]*\]\([^)]*\)")
AUTOLINK_RE = re.compile(r"<[A-Za-z][^>\n]*>")
URL_RE = re.compile(r"https?://\S+", re.IGNORECASE)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def looks_like_path(tok):
    """True if `tok` is a plausible path token (contains '/' or ends in a known ext)."""
    if not tok or tok in (".", "..", "..."):
        return False
    if not re.search(r"[A-Za-z0-9]", tok):
        # Reject punctuation-only tokens like a lone '/' between two words.
        return False
    if "/" in tok or "\\" in tok:
        return True
    return bool(re.search(r"\.(?:" + KNOWN_EXTS + r")$", tok))


def target_exists(base_dir, tok, known_missing):
    """Resolve `tok` against `base_dir` and report whether it exists on disk."""
    norm = tok.replace("\\", "/")
    # Skip absolute paths (Unix "/...", Windows "C:/...", UNC "//...") — those
    # are host/system paths (e.g. /proc/self/mounts), not repo-relative files.
    if norm.startswith("/") or re.match(r"^[A-Za-z]:/", norm):
        return False
    basename = os.path.basename(norm)
    if basename in known_missing:
        return True
    return os.path.exists(os.path.join(base_dir, norm))


def linkify_bare(text, base_dir, known_missing):
    """Replace existing bare path tokens in `text` with [path](path)."""
    def repl(m):
        tok = m.group(0)
        if looks_like_path(tok) and target_exists(base_dir, tok, known_missing):
            return "[%s](%s)" % (tok, tok)
        return tok

    return TOKEN_RE.sub(repl, text)


def process_line(line, base_dir, known_missing):
    """Process a single non-fence line: handle inline-code spans + bare paths."""
    parts = INLINE_CODE_RE.split(line)
    out = []
    for idx, part in enumerate(parts):
        if part == "":
            continue
        if idx % 2 == 1:
            # Inline code span (starts and ends with a backtick).
            content = part[1:-1].strip()
            if looks_like_path(content) and target_exists(base_dir, content, known_missing):
                out.append("[%s](%s)" % (content, content))
            else:
                out.append(part)
        else:
            out.append(linkify_bare(part, base_dir, known_missing))
    return "".join(out)


def transform(text, base_dir, known_missing):
    """Convert existing paths in a Markdown document's text to links."""
    protected = []

    def stash(m):
        protected.append(m.group(0))
        return "\x00%d\x00" % (len(protected) - 1)

    # 1. Protect existing links / autolinks / URLs so we never double-wrap them.
    text = MD_LINK_RE.sub(stash, text)
    text = AUTOLINK_RE.sub(stash, text)
    text = URL_RE.sub(stash, text)

    # 2. Process line by line, skipping fenced code blocks.
    out_lines = []
    in_fence = False
    for line in text.split("\n"):
        if FENCE_LINE_RE.match(line):
            in_fence = not in_fence
            out_lines.append(line)
            continue
        if in_fence:
            out_lines.append(line)
            continue
        out_lines.append(process_line(line, base_dir, known_missing))
    text = "\n".join(out_lines)

    # 3. Restore the protected spans.
    for i, s in enumerate(protected):
        text = text.replace("\x00%d\x00" % i, s)

    return text


def changed_lines(old, new):
    """Yield (old_line, new_line) pairs for lines that differ."""
    old_lines = old.split("\n")
    new_lines = new.split("\n")
    n = max(len(old_lines), len(new_lines))
    for i in range(n):
        o = old_lines[i] if i < len(old_lines) else ""
        n_ = new_lines[i] if i < len(new_lines) else ""
        if o != n_:
            yield o, n_


def iter_md_files(root):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if not d.startswith(".")]
        for fn in filenames:
            if fn.endswith((".md", ".markdown")):
                yield os.path.join(dirpath, fn)


def main():
    ap = argparse.ArgumentParser(
        description="Convert existing file paths in Markdown to [path](path) links.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    ap.add_argument("root", nargs="?", default=".", help="root directory to scan (default: .)")
    ap.add_argument("--apply", action="store_true", help="write changes back to disk")
    ap.add_argument("--backup", action="store_true", help="with --apply, keep a .bak of changed files")
    ap.add_argument(
        "--known-missing",
        default="",
        help="extra comma-separated filenames to treat as existing (e.g. tool-index.md)",
    )
    args = ap.parse_args()

    known_missing = set(KNOWN_MISSING)
    if args.known_missing:
        known_missing.update(s.strip() for s in args.known_missing.split(",") if s.strip())

    files_changed = 0
    replacements = 0

    for path in iter_md_files(args.root):
        with open(path, "r", encoding="utf-8") as f:
            original = f.read()

        base_dir = os.path.dirname(os.path.abspath(path))
        new = transform(original, base_dir, known_missing)

        if new == original:
            continue

        files_changed += 1

        if not args.apply:
            print("\n=== %s ===" % os.path.relpath(path))
            for old_line, new_line in changed_lines(original, new):
                print("- " + old_line)
                print("+ " + new_line)
                replacements += 1
        else:
            if args.backup:
                with open(path + ".bak", "w", encoding="utf-8") as f:
                    f.write(original)
            with open(path, "w", encoding="utf-8") as f:
                f.write(new)
            # cheap replacement count without re-diffing every line
            for old_line, new_line in changed_lines(original, new):
                replacements += 1

    if args.apply:
        print("Wrote %d file(s), %d changed line(s)." % (files_changed, replacements))
    else:
        print("\nDry run: %d file(s) would change (%d changed line(s))." % (files_changed, replacements))
        print("Re-run with --apply to write changes.")


if __name__ == "__main__":
    main()
